<div id="dv_enlacesinteres">
    <div class="contenedor_enlacesinteres">
        <!--div id="dv_infoenlacesinteres">Enlaces de Interes 1</div-->
        <div id="dv_certificaciones">
            <div id="dv_certificacioncalidad">
                <span id="sp_certificacioncalidad" class="etiqueta_certificacioncalidad">Certificación de Calidad</span>
                <div id="dv_contenidocertificacioncalidad">
                    <div><span id="sp_certificaciones">Certificación de</span></div>
                    <div><span id="sp_calidad">CALIDAD</span></div>
                </div>
            </div>
            <div  id="dv_iconoscertificacioncalidad">
                <div><img src="<?= PUBLIC_PATH?>img/ISO_9001.png"></div>
                <div><img src="<?= PUBLIC_PATH?>img/NTC_5555.png"></div>
                <div><img src="<?= PUBLIC_PATH?>img/Certificacion_Servicios.png"></div>
                <div><img src="<?= PUBLIC_PATH?>img/IQNet.png"></div>
            </div>
        </div>
    </div>
    <div class="contenedor_enlacesinteres">
        <div id="dv_imgenlacesinteres">
            <a class="contenedor_imgenlacesinteres" href="http://www.mineducacion.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_mineducacion.png"></a>
            <a class="contenedor_imgenlacesinteres" href="http://www.icetex.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_icetex.png"></a>
            <a class="contenedor_imgenlacesinteres" href="http://www.colciencias.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_colciencias.png"></a>
        </div>
    </div>
</div>
<div id="dv_informacion_instituto">
    <div>
        <span>Calle 21 No. 23-90. San Juan de Pasto - Colombia</span><span>. </span><span>Teléfono(s): (2)7212300 - (2)7208428</span><span>. </span><span>Email: instituto@institutotsc.com</span>
    </div>
    <div>
        <span>Copyright © Instituto Técnico Surcolombiano</span><span>. </span><span>Todos los derechos reservados</span>
    </div>
</div>