<div id="dv_enlacesinteres">
    <div class="contenedor_enlacesinteres">
        <div id="dv_infoenlacesinteres">Enlaces de Interes 1</div>
    </div>
    <div class="contenedor_enlacesinteres">
        <div id="dv_imgenlacesinteres">
            <a class="contenedor_imgenlacesinteres" href="http://www.mineducacion.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_mineducacion.png"></a>
            <a class="contenedor_imgenlacesinteres" href="http://www.icetex.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_icetex.png"></a>
            <a class="contenedor_imgenlacesinteres" href="http://www.colciencias.gov.co/" target="_blanck"><img src="<?= PUBLIC_PATH?>img/icon_colciencias.png"></a>
        </div>
    </div>
</div>
<div id="dv_informacion_instituto">
    <span>Calle 21 No. 23-90. San Juan de Pasto - Colombia. Teléfono(s): (2)7212300 - (2)7208428. Email: instituto@institutotsc.com</span>
    <span>Copyright © Instituto Técnico Surcolombiano. Todos los derechos reservados.</span>
</div>