<?//= $tipoPrograma?>
<?//= var_dump($tipoInstitucion)?>

<div id="dv_menu" class="contenedor_opcionesmenu">
    <div id="dv_opcionesmenu">
        <a class="contenedor_opcionmenu" href="<?= PUBLIC_PATH?>">
            <span class="etiqueta_iconopcionmenu icon_home_white"></span>
            <span class="etiqueta_tituloopcionmenu">Inicio</span>
        </a>
        <div id="dv_institucionopcionmenu" class="contenedor_opcionmenu">
            <span class="etiqueta_iconopcionmenu icon_institucion"></span>
            <span id="sp_institucionmenu" class="etiqueta_tituloopcionmenu">Institución</span>
            <span id="sp_institucionicondown" class="etiqueta_icondown icon_down"></span>
        </div>
        <div id="dv_institucionopcionesmenu" class="contenedor_opcionmenu contenedor_institucionopcionmenu">
            <div>
                <span class="etiqueta_iconopcionmenu"></span>
                <? if($banInstitucion > 0): ?>
                    <span id="sp_institucionmisionvision" class="etiqueta_instituciontituloopcionmenu">Misión | Visión</span>
                <? else: ?>
                    <a class="etiqueta_instituciontituloopcionmenu" href="<?= PUBLIC_PATH?>index/institucion/1">Misión | Visión</a>
                <? endif; ?>
            </div>
            <div>
                <span class="etiqueta_iconopcionmenu"></span>
                <? if($banInstitucion > 0): ?>
                    <span id="sp_institucionvisitanos" class="etiqueta_instituciontituloopcionmenu">Visítanos</span>
                <? else: ?>
                    <a class="etiqueta_instituciontituloopcionmenu" href="<?= PUBLIC_PATH?>index/institucion/2">Visítanos</a>
                <? endif; ?>
            </div>
        </div>
        <div id="dv_programasopcionmenu" class="contenedor_opcionmenu">
            <span class="etiqueta_iconopcionmenu icon_programs"></span>
            <span id="sp_programasmenu" class="etiqueta_tituloopcionmenu">Programas</span>
            <span id="sp_programasicondown" class="etiqueta_icondown icon_down"></span>
        </div>
        <div id="dv_programasopcionesmenu" class="contenedor_opcionmenu contenedor_institucionopcionmenu">
            <div id="dv_programasteclab">
                <span class="etiqueta_iconopcionmenu"></span>
                <? if($banProgramas > 0): ?>
                    <span id="sp_programasteclab" class="etiqueta_instituciontituloopcionmenu">Técnico Laborales</span>
                <? else: ?>
                    <a class="etiqueta_instituciontituloopcionmenu" href="<?= PUBLIC_PATH?>program/programas/1">Técnico Laborales</a>
                <? endif; ?>
            </div>
            <div>
                <span class="etiqueta_iconopcionmenu"></span>
                <? if($banProgramas > 0): ?>
                    <span id="sp_programasinglesniv" class="etiqueta_instituciontituloopcionmenu">Ingles Por Niveles</span>
                <? else: ?>
                    <a class="etiqueta_instituciontituloopcionmenu" href="<?= PUBLIC_PATH?>program/programas/7">Ingles Por Niveles</a>
                <? endif; ?>
            </div>
        </div>
        <a class="contenedor_opcionmenu" href="#">
            <span class="etiqueta_iconopcionmenu icon_campus"></span>
            <span class="etiqueta_tituloopcionmenu">Campus Virtual</span>
        </a>
        <a class="contenedor_opcionmenu" href="<?= PUBLIC_PATH?>registration/preinscripcion/">
            <span class="etiqueta_iconopcionmenu icon_contact"></span>
            <span class="etiqueta_tituloopcionmenu">Preinscripción</span>
        </a>
        <div id="dv_noopcionmenu"><div></div></div>
    </div>
    <div id="dv_cerrarmenu">
        <span id="sp_cerrarmenu" class="icon_cerrarmenu"></span>
    </div>
    <div id="dv_backmenu"></div>
</div>

<div id="dv_fechahora">
    <? $dia = date("j");
    $anio = date("Y");
    $meses = array("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"); ?>
    
    San Juan de Pasto, <?= $meses[date('n')-1] . ' ' . $dia . ' del ' . $anio?>
</div>
<div id="dv_logo">
    <span id="sp_menu" class="icon_menu"></span>
    <img src="<?= PUBLIC_PATH?>img/logo.png">
</div>
<div id="dv_instituto">INSTITUTO TÉCNICO SURCOOMBIANO</div>
<div id="dv_navegacion">
    <div class="btn">
        <a class="dropbtn" href="<?= PUBLIC_PATH?>" style="position: relative;">Inicio</a>
    </div>
    <div class="btn dropdown">
        <span id="sp_instituciong" class="dropbtn active">Institución</span>
        <?/* if($banInstitucion > 0): ?>
            <span id="sp_instituciong" class="dropbtn active">Institución</span>
        <? else: ?>
            <a class="dropbtn" href="<?= PUBLIC_PATH?>index/institucion/3" style="position: relative;">Institución</a>
        <? endif; */?>
        <div class="dropdown-content">
            <? if($banInstitucion > 0): ?>
                <span id="sp_institucionmv">Misión | Visión</span>
                <span id="sp_institucionv">Visítanos</span>
            <? else: ?>
                <a href="<?= PUBLIC_PATH?>index/institucion/1">Misión | Visión</a>
                <a href="<?= PUBLIC_PATH?>index/institucion/2">Visítanos</a>
            <? endif; ?>
        </div>
    </div>
    <div class="btn dropdown">
        <!--a id="sp_programas1" class="dropbtn" href="<?= PUBLIC_PATH?>program/programas/" style="position: relative;">Programas</a-->
        <span class="dropbtn">Programas</span>
        <div id="prueba" class="dropdown-content">
            <? if($banProgramas > 0): ?>
                <span id="sp_teclab">Técnico Laborales</span>
                <span id="sp_inglesniv">Ingles Por Niveles</span>
            <? else: ?>
                <!--a href="<?= PUBLIC_PATH?>program/tecnicos/<?= ($banProgramas>0)?1:0;?>">Técnico Laborales</a>
                <a href="<?= PUBLIC_PATH?>program/ingles/<?= ($banProgramas>0)?1:0;?>">Ingles Por Niveles</a-->
                <a href="<?= PUBLIC_PATH?>program/programas/1">Técnico Laborales</a>
                <a href="<?= PUBLIC_PATH?>program/programas/7">Ingles Por Niveles</a>
            <? endif; ?>
                        
            <!--span>Técnico Laboral en Administración de Gestión del Talento Humano</span>
            <span>Técnico Laboral en Gestión Contable y Financiero</span>
            <span>Técnico Laboral en Preparación Física y Entrenamiento Deportivo</span>
            <span>Técnico Laboral en Sistemas</span>
            <span>Técnico Laboral en Vigilancia, Seguridad y Control de Instalaciones</span-->
        </div>
    </div>
    <div class="btn">
        <a class="dropbtn" href="#" style="position: relative;">Campus Virtual</a>
    </div>
    <div class="btn">
        <a class="dropbtn" href="<?= PUBLIC_PATH?>registration/preinscripcion/" style="position: relative;">Preinscripción</a>
    </div>
</div>
<div id="dv_navegacionsec" class="contenedor_navegacionsec contendor_navegacionsecdn">
    <!--span id="sp_iniciox" class="contendor_navegacionsecdn navsecnoactive">Inicio</span-->
    <a id="lnk_inicio" href="<?= PUBLIC_PATH?>"><span id="sp_inicio" class="contendor_navegacionsecdn icon_home"></span></a>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_institucion" class="contendor_navegacionsecdn navsecnoactive">Institución</span>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_institucionopc" class="contendor_navegacionsecdn navsecactive"></span>
    <span id="sp_programas" class="contendor_navegacionsecdn navsecnoactive">Programas</span>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_programa" class="contendor_navegacionsecdn navsecactive"></span>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_programateclab" class="contendor_navegacionsecdn navsecactive"></span>
</div>

<script type="text/javascript">
    $(window).load(function(){
        <? if($banInstitucion > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            //$('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            
            <? if($tipoInstitucion === '1'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
            <? elseif($tipoInstitucion === '2'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
            <? else: ?>
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').addClass('navsecactive');
            <? endif; ?>
        <? elseif($banProgramas > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            
            <? switch($tipoPrograma):
                case 1: ?>
                    $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                case 7: ?>
                    $('#sp_programa').text('Ingles Por Niveles').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                default:
                    break;
            endswitch;?>
        <? endif; ?>
    });
    
    $('.dropdown').on('mouseover', function (){
        var top = $(this).offset().top,
            left = $(this).offset().left;
        
        /*if($(this).find('#prueba')){
            console.log("True");
        }else{
            console.log("False");
        }*/
        
        $(this).find('.dropdown-content').css({display: 'flex', top: top + 40, left: left - 30});
    });
    
    $('.dropdown').on('mouseout', function (){
        $(this).find('.dropdown-content').css({display: 'none'});
    });
    
    /*$('#sp_instituciong, #sp_institucion').on('click', function (){*/
    $('#sp_institucion').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/institucion/3",
            data: {
                'tipoIns': 3
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive').addClass('navsecactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').addClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionmv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/institucion/",
            url: window.public_path + "index/institucion/1",
            data: {
                'tipoIns': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionmisionvision').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/institucion/",
            url: window.public_path + "index/institucion/1",
            data: {
                'tipoIns': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
                
                $('body').removeClass('menuopen');
                $drawer.removeClass('opcionesmenuopen');
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/visitanos/",
            url: window.public_path + "index/institucion/2",
            data: {
                'tipoIns': 2
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionvisitanos').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/visitanos/",
            url: window.public_path + "index/institucion/2",
            data: {
                'tipoIns': 2
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
                
                $('body').removeClass('menuopen');
                $drawer.removeClass('opcionesmenuopen');            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_teclab').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/tecnicos/1",
            url: window.public_path + "program/programas/1",
            data: {
                'tipoProg': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                
                $('#sp_teclab').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_programasteclab').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/tecnicos/1",
            url: window.public_path + "program/programas/1",
            data: {
                'tipoProg': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                $('#sp_teclab').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
                
                $('body').removeClass('menuopen');
                $drawer.removeClass('opcionesmenuopen');
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_inglesniv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/ingles/1",
            url: window.public_path + "program/programas/7",
            data: {
                'tipoProg': 7
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Ingles Por Niveles').removeClass('contendor_navegacionsecdn');
                $('#sp_inglesniv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_programasinglesniv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/ingles/1",
            url: window.public_path + "program/programas/7",
            data: {
                'tipoProg': 7
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Ingles Por Niveles').removeClass('contendor_navegacionsecdn');
                $('#sp_inglesniv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
                
                $('body').removeClass('menuopen');
                $drawer.removeClass('opcionesmenuopen');
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    /*$('#sp_inicio').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/index/",
            data: {
                'banInicio': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });*/
    
    var $menu = $('#sp_menu'),
        $drawer = $('#dv_menu'),
        $close = $('#dv_cerrarmenu');
        //$back = $('#dv_backmenu);
    
    $drawer.on('click',function(e){
        //e.stopPropagation();
    });
    
    $menu.on('click', function(e) {
        e.stopPropagation();
        
        var altura = $('#dv_opcionesmenu').height() - 305;
        
        $('body').addClass('menuopen');
        
        if(altura > 0){
            $('#dv_noopcionmenu').css({width: '100%', height: altura});
            $('#dv_noopcionmenu div').css({width: '60px', height: '100%', 'background-color': '#00529B'});
        }
        
        $drawer.toggleClass('opcionesmenuopen');
    });
    
    $close.on('click', function() {
        $('body').removeClass('menuopen');
        $drawer.removeClass('opcionesmenuopen');
    });
    
    $(window).resize(function(){
        var altura = $('#dv_opcionesmenu').height() - 305;
        
        if(altura > 0){
            $('#dv_noopcionmenu').css({width: '100%', height: altura});
            $('#dv_noopcionmenu div').css({width: '60px', height: '100%', 'background-color': '#00529B'});
        }else{
            $('#dv_noopcionmenu').css({width: '100%', height: '0'});
        }
    });
    
    $('#dv_institucionopcionmenu').on('click', function(){
        $('#dv_institucionopcionesmenu').slideToggle();
        $('#sp_institucionmenu').toggleClass('etiqueta_tituloopcionmenuseleccionada');
        $('#sp_institucionicondown').toggleClass('icon_up');
        $('#dv_institucionopcionmenu').toggleClass('contenedor_opcionmenuseleccionada');
    });
    
    $('#dv_programasopcionmenu').on('click', function(){
        $('#dv_programasopcionesmenu').slideToggle();
        $('#sp_programasmenu').toggleClass('etiqueta_tituloopcionmenuseleccionada');
        $('#sp_programasicondown').toggleClass('icon_up');
        $('#dv_programasopcionmenu').toggleClass('contenedor_opcionmenuseleccionada');
    });
</script>