<?//= $tipoPrograma?>
<?//= var_dump($tipoInstitucion)?>

<div id="dv_fechahora">
    <? $dia = date("j");
    $anio = date("Y");
    $meses = array("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"); ?>
    
    San Juan de Pasto, <?= $meses[date('n')-1] . ' ' . $dia . ' del ' . $anio?>
</div>
<div id="dv_logo">
    <!--div>LOGO</div-->
    <img src="<?= PUBLIC_PATH?>img/logo.png">
</div>
<div id="dv_instituto">INSTITUTO TÉCNICO SURCOOMBIANO</div>
<div id="dv_navegacion">
    <div class="btn">
        <a class="dropbtn" href="<?= PUBLIC_PATH?>" style="position: relative;">Inicio</a>
    </div>
    <div class="btn dropdown">
        <? if($banInstitucion > 0): ?>
            <span id="sp_instituciong" class="dropbtn active">Institución</span>
        <? else: ?>
            <a class="dropbtn" href="<?= PUBLIC_PATH?>index/institucion/3" style="position: relative;">Institución</a>
        <? endif; ?>
        <div class="dropdown-content">
            <? if($banInstitucion > 0): ?>
                <span id="sp_institucionmv">Misión | Visión</span>
                <span id="sp_institucionv">Visítanos</span>
            <? else: ?>
                <a href="<?= PUBLIC_PATH?>index/institucion/1">Misión | Visión</a>
                <a href="<?= PUBLIC_PATH?>index/institucion/2">Visítanos</a>
            <? endif; ?>
        </div>
    </div>
    <div class="btn dropdown">
        <!--a id="sp_programas1" class="dropbtn" href="<?= PUBLIC_PATH?>program/programas/" style="position: relative;">Programas</a-->
        <span class="dropbtn">Programas</span>
        <div id="prueba" class="dropdown-content">
            <? if($banProgramas > 0): ?>
                <span id="sp_teclab">Técnico Laborales</span>
                <span id="sp_inglesniv">Ingles Por Niveles</span>
            <? else: ?>
                <!--a href="<?= PUBLIC_PATH?>program/tecnicos/<?= ($banProgramas>0)?1:0;?>">Técnico Laborales</a>
                <a href="<?= PUBLIC_PATH?>program/ingles/<?= ($banProgramas>0)?1:0;?>">Ingles Por Niveles</a-->
                <a href="<?= PUBLIC_PATH?>program/programas/1">Técnico Laborales</a>
                <a href="<?= PUBLIC_PATH?>program/programas/7">Ingles Por Niveles</a>
            <? endif; ?>
                        
            <!--span>Técnico Laboral en Administración de Gestión del Talento Humano</span>
            <span>Técnico Laboral en Gestión Contable y Financiero</span>
            <span>Técnico Laboral en Preparación Física y Entrenamiento Deportivo</span>
            <span>Técnico Laboral en Sistemas</span>
            <span>Técnico Laboral en Vigilancia, Seguridad y Control de Instalaciones</span-->
        </div>
    </div>
    <div class="btn">
        <a class="dropbtn" href="#" style="position: relative;">Campus Virtual</a>
    </div>
    <div class="btn">
        <a class="dropbtn" href="<?= PUBLIC_PATH?>registration/preinscripcion/" style="position: relative;">Preinscripción</a>
    </div>
</div>
<div id="dv_navegacionsec" class="contenedor_navegacionsec contendor_navegacionsecdn">
    <!--span id="sp_iniciox" class="contendor_navegacionsecdn navsecnoactive">Inicio</span-->
    <a id="lnk_inicio" href="<?= PUBLIC_PATH?>"><span id="sp_inicio" class="contendor_navegacionsecdn icon_home"></span></a>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_institucion" class="contendor_navegacionsecdn navsecnoactive">Institución</span>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_institucionopc" class="contendor_navegacionsecdn navsecactive"></span>
    <span id="sp_programas" class="contendor_navegacionsecdn navsecnoactive">Programas</span>
    <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
    <span id="sp_programa" class="contendor_navegacionsecdn navsecactive"></span>
</div>

<script type="text/javascript">
    $(window).load(function(){
        <? if($banInstitucion > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            //$('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            
            <? if($tipoInstitucion === '1'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
            <? elseif($tipoInstitucion === '2'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
            <? else: ?>
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').addClass('navsecactive');
            <? endif; ?>
        <? elseif($banProgramas > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            
            <? switch($tipoPrograma):
                case 1: ?>
                    $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                case 7: ?>
                    $('#sp_programa').text('Ingles Por Niveles').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                default:
                    break;
            endswitch;?>
        <? endif; ?>
    });
    
    $('.dropdown').on('mouseover', function (){
        var top = $(this).offset().top,
            left = $(this).offset().left;
        
        /*if($(this).find('#prueba')){
            console.log("True");
        }else{
            console.log("False");
        }*/
        
        $(this).find('.dropdown-content').css({display: 'flex', top: top + 40, left: left - 30});
    });
    
    $('.dropdown').on('mouseout', function (){
        $(this).find('.dropdown-content').css({display: 'none'});
    });
    
    $('#sp_instituciong, #sp_institucion').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/institucion/3",
            data: {
                'tipoIns': 3
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive').addClass('navsecactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').addClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionmv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/institucion/",
            url: window.public_path + "index/institucion/1",
            data: {
                'tipoIns': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "index/visitanos/",
            url: window.public_path + "index/institucion/2",
            data: {
                'tipoIns': 2
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_teclab').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/tecnicos/1",
            url: window.public_path + "program/programas/1",
            data: {
                'tipoProg': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                $('#sp_teclab').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_inglesniv').on('click', function (){
        $.ajax({
            type: 'POST',
            //url: window.public_path + "program/ingles/1",
            url: window.public_path + "program/programas/7",
            data: {
                'tipoProg': 7
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                //$('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Ingles Por Niveles').removeClass('contendor_navegacionsecdn');
                $('#sp_inglesniv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    /*$('#sp_inicio').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/index/",
            data: {
                'banInicio': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });*/
</script>