<!--div id="dv_fechahora">
    <? $dia = date("j");
    $anio = date("Y");
    $meses = array("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"); ?>

    San Juan de Pasto, <?= $meses[date('n')-1] . ' ' . $dia . ' del ' . $anio?>
</div-->
<div id="<?= ($view<=0)?'dv_logo':'dv_logoalterno';?>">
    <? if($view <= 0) : ?>
        <span id="sp_menu" class="icon_menu"></span>
    <? endif; ?>
    <img src="<?= PUBLIC_PATH?>img/logo.png" alt="Logo Instituto Técnico Surcolombiano">
</div>
<div id="<?= ($view<=0)?'dv_instituto':'dv_institutoalterno';?>">
    <?= ($view<=0)?'<h1>INSTITUTO TÉCNICO SURCOLOMBIANO</h1>':'<h1>' . $titulosc . '</h1><span>INSTITUTO TÉCNICO SURCOLOMBIANO</span>';?>
</div>
<? if($view <= 0) : ?>
    <div id="dv_navegacion">
        <div class="btn">
            <a class="dropbtn" href="<?= PUBLIC_PATH?>" style="position: relative;">Inicio</a>
        </div>
        <div class="btn dropdown">
            <span id="sp_instituciong" class="dropbtn active">Institución</span>
            <div class="dropdown-content">
                <? if($banInstitucion > 0): ?>
                    <span id="sp_institucionmv">Misión | Visión</span>
                    <span id="sp_institucionv">Visítanos</span>
                <? else: ?>
                    <!--a href="<?= PUBLIC_PATH?>index/institucion/1">Misión | Visión</a-->
                    <a href="<?= PUBLIC_PATH?>institucion/mision_vision">Misión | Visión</a>
                    <!--a href="<?= PUBLIC_PATH?>index/institucion/2">Visítanos</a-->
                    <a href="<?= PUBLIC_PATH?>institucion/visitanos">Visítanos</a>
                <? endif; ?>
            </div>
        </div>
        <div class="btn dropdown">
            <span class="dropbtn">Programas</span>
            <div id="prueba" class="dropdown-content">
                <? if($banProgramas > 0): ?>
                    <span id="sp_teclab">Técnico Laborales</span>
                    <span id="sp_curso">Cursos, Seminarios y Diplomados</span>
                <? else: ?>
                    <!--a href="<?= PUBLIC_PATH?>program/programas/1">Técnico Laborales</a-->
                    <a href="<?= PUBLIC_PATH?>programas/tecnico_laborales">Técnico Laborales</a>
                    <!--a href="<?= PUBLIC_PATH?>program/programas/7">Cursos, Seminarios y Diplomados</a-->
                    <a href="<?= PUBLIC_PATH?>programas/cursos_seminarios_diplomados">Cursos, Seminarios y Diplomados</a>
                <? endif; ?>
            </div>
        </div>
        <div class="btn dropdown">
            <span class="dropbtn">Servicios</span>
            <div id="prueba" class="dropdown-content">
                <a href="<?= PUBLIC_PATH?>estudiantes/consulta_notas">Consulta de Notas</a>
                <a href="<?= PUBLIC_PATH?>docentes/inicio">Registro de Notas</a>
                <a href="<?= PUBLIC_PATH?>evaluation/evaluacionDocente">Evaluación Docente</a>
            </div>
        </div>
        <!--div class="btn">
            <a class="dropbtn" href="#" style="position: relative;">Campus Virtual</a>
        </div-->
        <div class="btn">
            <!--a class="dropbtn" href="<?= PUBLIC_PATH?>registration/preinscripcion/" style="position: relative;">Preinscripción</a-->
            <!--a class="dropbtn" href="<?= PUBLIC_PATH?>index/contactenos/" style="position: relative;">Contáctenos</a-->
            <a class="dropbtn" href="<?= PUBLIC_PATH?>institucion/contactenos" style="position: relative;">Contáctenos</a>
        </div>
    </div>
    <div id="dv_navegacionsec" class="contenedor_navegacionsec contendor_navegacionsecdn">
        <a id="lnk_inicio" href="<?= PUBLIC_PATH?>"><span id="sp_inicio" class="contendor_navegacionsecdn icon_home"></span></a>
        <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
        <span id="sp_institucion" class="contendor_navegacionsecdn navsecnoactive">Institución</span>
        <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
        <span id="sp_institucionopc" class="contendor_navegacionsecdn navsecactive"></span>
        <span id="sp_programas" class="contendor_navegacionsecdn navsecnoactive">Programas</span>
        <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
        <span id="sp_programa" class="contendor_navegacionsecdn navsecactive"></span>
        <span class="icon_next etiqueta_next contendor_navegacionsecdn"></span>
        <span id="sp_programateclab" class="contendor_navegacionsecdn navsecactive"></span>
    </div>
<? else:
    if($view > 1 && Auth::is_valid()): ?>
        <div style="width: 100%; height: 60px; background-color: #ffffff">
            <div>
                <span>Bienvenido Profesor</span>
                <span><?= Auth::get('nombre_docente') . ' ' . Auth::get('apellido_docente')?></span>
            </div>
            <button onclick="window.location = '<?= PUBLIC_PATH?>grade/salirDocente'">Salir</button>
        </div>
    <? endif;
endif; ?>

<script type="text/javascript">
    $(window).load(function(){
        <? if($banInstitucion > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            
            <? if($tipoInstitucion === '1'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
            <? elseif($tipoInstitucion === '2'): ?>
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
            <? else: ?>
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').addClass('navsecactive');
            <? endif;
        elseif($banProgramas > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            
            <? switch($tipoPrograma):
                case 1: ?>
                    $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                case 7: ?>
                    $('#sp_programa').text('Cursos, Seminarios y Diplomados').removeClass('contendor_navegacionsecdn');
                    
                    <? break;
                default:
                    break;
            endswitch;
        elseif($banContactenos > 0): ?>
            $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
            $('#sp_inicio').removeClass('contendor_navegacionsecdn');
            $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_institucion').addClass('etiqueta_institucion');
            $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
            $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
            $('#sp_institucionopc').text('Contáctenos').removeClass('contendor_navegacionsecdn');
        <? endif; ?>
    });
    
    $("document").ready(function($){
        /*var header = $('header'),
            logo = $('#dv_logo'),
            imgLogo = $('#dv_logo img'),
            its = $('#dv_instituto'),
            nav = $('#dv_navegacion'),
            itemNav = $('#dv_navegacion .btn'),
            navSec = $('#dv_navegacionsec'),
            contenido = $('#sec_contenido');*/
        
        var navSec = $('#dv_navegacionsec'),
            contenido = $('#sec_contenido');

        pos = $('header').offset(),
        alth = $('header').height(),
        altns = $('#dv_navegacionsec').height();

        $(window).scroll(function () {
            if ($(this).scrollTop() > (pos.top + alth - altns)) {
                window.navegacion = 1;
                
                /*if (window.innerWidth > 768) {
                    header.css({
                        height: '40px',
                        background: 'linear-gradient(to bottom, #00529B 0%, #2989d8 100%, #207cca 100%, #7db9e8 100%)',
                        position: 'fixed',
                        top: '0',
                        left: pos.left,
                        'z-index': '100',
                        'max-width': '1024px',
                        'justify-content': 'flex-end'
                    });
                    logo.css({
                        width: '10%',
                        height: '30px',
                        padding: '5px 0'
                    });
                    imgLogo.css({
                        width: '30px',
                        height: '30px',
                        margin: '0'
                    });
                    its.css({
                        width: '40%',
                        height: '40px',
                        'font-size': '20px',
                        'letter-spacing': '0',
                        display: 'flex',
                        'align-items': 'center',
                        'justify-content': 'center'
                    });
                    nav.css({
                        width: '50%'
                    });
                    itemNav.css({
                        width: '25%'
                    });
                    contenido.css({
                        padding: '40px 0 0 0'
                    });
                }*/
                
                if (window.innerWidth <= 768) {
                    navSec.css({
                        display: 'none'
                    });
                    contenido.css({
                        padding: '60px 0 0 0'
                    });
                }
                
                //header.addClass("navegacion");
            } else {
                window.navegacion = 0;

                /*header.removeClass('navegacion');
                header.removeAttr('style');
                logo.removeAttr('style');
                imgLogo.removeAttr('style');
                its.removeAttr('style');
                nav.removeAttr('style');
                itemNav.removeAttr('style');*/
                navSec.removeAttr('style');
                contenido.removeAttr('style');
            }
        });
    });
    
    $(window).resize(function(){
        pos = $('header').offset(),
        alth = $('header').height(),
        altns = $('#dv_navegacionsec').height();
    });
    
    $('.dropdown').on('mouseover', function (){
        var top = $(this).offset().top,
            left = $(this).offset().left;
        
        pos = $('#dv_navegacion').offset();
        
        if(window.navegacion > 0){
            $(this).find('.dropdown-content').css({display: 'flex', position: 'fixed', top: 40, left: left - 30});
        }else{
            $(this).find('.dropdown-content').css({display: 'flex', position: 'absolute', top: pos.top + 40, left: left - 30});
        }
    });
    
    $('.dropdown').on('mouseout', function (){
        $(this).find('.dropdown-content').removeAttr('style');
        $(this).find('.dropdown-content').css({display: 'none'});
    });
    
    /*$('#sp_instituciong, #sp_institucion').on('click', function (){*/
    $('#sp_institucion').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/institucion/3",
            data: {
                'tipoIns': 3
            },
            beforeSend: function(){

            },
            success: function(data){
                history.pushState(null, "", "<?= PUBLIC_PATH?>institucion");
                
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').removeClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecnoactive').addClass('navsecactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').addClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                
                <? if($banContactenos > 0): ?>
                    window.location = "<?= PUBLIC_PATH?>index/institucion/3"
                <? else: ?>
                    $('#sec_contenido').html(data);
                <? endif; ?>
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionmv').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/institucion/1",
            data: {
                'tipoIns': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                history.pushState(null, "", "<?= PUBLIC_PATH?>institucion/mision_vision");
                
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Misión | Visión').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionmv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_institucionv').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "index/institucion/2",
            data: {
                'tipoIns': 2
            },
            beforeSend: function(){

            },
            success: function(data){
                history.pushState(null, "", "<?= PUBLIC_PATH?>institucion/visitanos");
                
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucion').addClass('etiqueta_institucion');
                $('#sp_institucion').removeClass('navsecactive').addClass('navsecnoactive');
                $('#sp_institucion').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionopc').text('Visítanos').removeClass('contendor_navegacionsecdn');
                $('#sp_institucionv').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_teclab').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/programas/1",
            data: {
                'tipoProg': 1
            },
            beforeSend: function(){

            },
            success: function(data){
                history.pushState(null, "", "<?= PUBLIC_PATH?>programas/tecnico_laborales");
                
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').removeClass('contendor_navegacionsecdn');
                
                $('#sp_teclab').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_curso').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/programas/7",
            data: {
                'tipoProg': 7
            },
            beforeSend: function(){

            },
            success: function(data){
                history.pushState(null, "", "<?= PUBLIC_PATH?>programas/cursos_seminarios_diplomados");
                
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn');
                $('#lnk_inicio').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').addClass('contendor_navegacionsecdn');
                $('#sp_programa').removeClass('navsecnoactive').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Cursos, Seminarios y Diplomados').removeClass('contendor_navegacionsecdn');
                $('#sp_curso').parent().css({display: 'none'});
                $('#sec_contenido').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
</script>