<div class="contenedor_imgprograma">
    <div>
        <span class="etiqueta_titprog"><?= $nomPrograma?></span>
    </div>
    <? switch($idPrograma):
        case 2: ?>
            <img src="<?= PUBLIC_PATH?>img/slider/info_talentohumano.jpg" alt="Administración del Talento Humano">
            
            <? break;
        case 3: ?>
            <img src="<?= PUBLIC_PATH?>img/slider/info_contabilidad.jpg" alt="Gestión Contable y Financiera">
            
            <? break;
        case 4: ?>
            <img src="<?= PUBLIC_PATH?>img/slider/info_deportes.jpg" alt="Preparación Fisica y Entrenamiento Deportivo">
            
            <? break;
        case 5: ?>
            <img src="<?= PUBLIC_PATH?>img/slider/sistemas.jpg" alt="Sistemas">
            
            <? break;
        case 6: ?>
            <img src="<?= PUBLIC_PATH?>img/slider/info_vigilancia.jpg" alt="Vigilancia, Seguridad y Control de Instalaciones">
            
            <? break;
        default:
            break;
    endswitch; ?>
</div>
<div class="contenedor_detalleprograma">
    <div class="contenedor_secciondetalleprograma">
        <span class="etiqueta_certificadoprograma">CERTIFICADO<br><?= $certificado?></span>
        <span class="etiqueta_tituloinformacionprograma">DESEMPÉÑATE COMO:</span>
        <div class="contenedor_informacionprograma">
            <ul>
                <? foreach($desempeno as $d): ?>
                    <li><?= $d?></li>
                <? endforeach; ?>
            </ul>
        </div>
        <span class="etiqueta_tituloinformacionprograma">ÁREAS DE FORMACIÓN</span>
        <div class="contenedor_informacionprograma">
            <ul>
                <? foreach($area as $a): ?>
                    <li><?= $a?></li>
                <? endforeach; ?>
            </ul>
        </div>
    </div>
</div>