<div class="contenedor_imgprograma">
    <img src="<?= PUBLIC_PATH?>img/slider/tecnicolaborales.jpg" alt="Técnico Laborales Instituto Técnico Surcolombiano">
</div>
<div class="contenedor_programa">
    <span class="etiqueta_titcurso">Cursos Libres</span>
    <ul>
        <li>Contabilidad Básica</li>
        <li>Contabilidad Básica</li>
        <li>Contabilidad Avanzada</li>
        <li>Manejo del Programa Contable SIIGO</li>
        <li>Mantenimiento de Computadores y Portatiles</li>
        <li>Sistemas Operativos y Ofimática (Word, Excel)</li>
        <li>Excel Avanzado</li>
        <li>Photoshop y Corel Draw</li>
        <li>Ilustrator</li>
    </ul>
    <span class="etiqueta_titcurso">Cursos Convenio<br>Academia de Capacitación de Seguridad El Pentagono LTDA</span>
    <ul>
        <li>Vigilancia</li>
        <li>Escolta</li>
        <li>Supervisor</li>
        <li>Medios Tecnológicos</li>
    </ul>
    <span class="etiqueta_titcurso">Cursos Especiales</span>
    <ul>
        <li>Ingles Básico y Avanzado</li>
    </ul>
    <span class="etiqueta_titcurso">Seminarios y Diplomados</span>
    <ul>
        <li>Emprendimiento</li>
        <li>Atención Integral al Niño</li>
        <li>Atención al Cliente</li>
        <li>Competencias Claves</li>
        <li>Hoja de Vida y Entrevista</li>
        <li>Creación y Constitutción de Empresas</li>
        <li>Trabajo en Equipo</li>
        <li>Finanzas</li>
        <li>Competencias Transversales</li>
    </ul>
</div>