<div id="dv_contenidoprograma">
    <div id="dv_programa"></div>
    <div id="dv_navprograma">
        <div>
            <span class="etiqueta_programas">Programas</span>
            <span class="etiqueta_tipprog">Técnico Laborales</span>
            <span class="etiqueta_nomprograma" data-programa="2">En Administración Talento Humano</span>
            <span class="etiqueta_nomprograma" data-programa="3">En Gestión Contable y Financiero</span>
            <span class="etiqueta_nomprograma" data-programa="4">En Preparación Física y Entrenamiento Deportivo</span>
            <span class="etiqueta_nomprograma" data-programa="5">En Sistemas</span>
            <span class="etiqueta_nomprograma" data-programa="6">En Vigilancia, Seguridad y Control de Instalaciones</span>
            <span id="sp_cursos" class="etiqueta_tipprograma" data-programa="8">Cursos, Seminarios y Diplomados</span>
            <!--span id="sp_ingles" class="etiqueta_tipprograma" data-programa="7">Ingles Por Niveles</span-->
        </div>
    </div>
</div>

<script type="text/javascript">
    <? switch($tipoProg):
        case 1: ?>
            $.ajax({
                type: 'POST',
                url: window.public_path + "program/tecnicos/",
                data: {},
                beforeSend: function(){

                },
                success: function(data){
                    //$('#sec_contenido').html(data);
                    $('#dv_programa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
            
            <? break;
        case 7: ?>
            $.ajax({
                type: 'POST',
                url: window.public_path + "program/cursos/",
                data: {},
                beforeSend: function(){

                },
                success: function(data){
                    //$('#sec_contenido').html(data);
                    $('#dv_programa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
            
            <? break;
        default:
            break;
    endswitch; ?>
    
    $('.etiqueta_nomprograma').on('click', function (){
        var idPrograma = $(this).data('programa'),
            str = $(this).text(),
            nomPrograma = str.replace("En ", ""),
            res = str.replace("En ", "en "),
            programa = "Técnico Laboral " + res;
            //nomPrograma = "Técnico Laboral " + $(this).text();
        
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/detallePrograma/",
            data: {
                'idPrograma': idPrograma,
                'nomPrograma': programa
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').addClass('navsecnoactive').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').next('span').removeClass('contendor_navegacionsecdn');
                //$('#sp_programateclab').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#dv_programa').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    $('#sp_cursos').on('click', function (){
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/cursos/",
            data: {},
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').addClass('contendor_navegacionsecdn').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programateclab').text('Cursos, Seminarios y Diplomados').removeClass('contendor_navegacionsecdn');
                $('#dv_programa').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
    
    /*$('#sp_ingles').on('click', function (){
        var idPrograma = $(this).data('programa'),
            nomPrograma = $(this).text();
        
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/detallePrograma/",
            data: {
                'idPrograma': idPrograma,
                'nomPrograma': nomPrograma
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').addClass('contendor_navegacionsecdn').next('span').addClass('contendor_navegacionsecdn');
                $('#sp_programateclab').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#dv_programa').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });*/
</script>