<div class="contenedor_imgprograma"></div>
<div class="contenedor_programa">
    <span class="etiqueta_titprog">Técnico Laborales</span>
    <span class="etiqueta_nomprog" data-programa="2">Técnico Laboral en Administración de Gestión del Talento Humano</span>
    <span class="etiqueta_nomprog" data-programa="3">Técnico Laboral en Gestión Contable y Financiero</span>
    <span class="etiqueta_nomprog" data-programa="4">Técnico Laboral en Preparación Física y Entrenamiento Deportivo</span>
    <span class="etiqueta_nomprog" data-programa="5">Técnico Laboral en Sistemas</span>
    <span class="etiqueta_nomprog" data-programa="6">Técnico Laboral en Vigilancia, Seguridad y Control de Instalaciones</span>
</div>

<script type="text/javascript">
    $('.etiqueta_nomprog').on('click', function (){
        var idPrograma = $(this).data('programa'),
            nomPrograma = $(this).text();
        
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/detallePrograma/",
            data: {
                'idPrograma': idPrograma,
                'nomPrograma': nomPrograma
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#dv_programa').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
</script>