<div class="contenedor_imgprograma">
    <img src="<?= PUBLIC_PATH?>img/slider/tecnicolaborales.jpg">
</div>
<div class="contenedor_programa">
    <span class="etiqueta_titprog">Técnico Laborales</span>
    <span class="etiqueta_nomprog" data-programa="2">Técnico Laboral en Administración del Talento Humano</span>
    <span class="etiqueta_nomprog" data-programa="3">Técnico Laboral en Gestión Contable y Financiero</span>
    <span class="etiqueta_nomprog" data-programa="4">Técnico Laboral en Preparación Física y Entrenamiento Deportivo</span>
    <span class="etiqueta_nomprog" data-programa="5">Técnico Laboral en Sistemas</span>
    <span class="etiqueta_nomprog" data-programa="6">Técnico Laboral en Vigilancia, Seguridad y Control de Instalaciones</span>
</div>

<script type="text/javascript">
    $('.etiqueta_nomprog').on('click', function (){
        var idPrograma = $(this).data('programa'),
            programa = $(this).text(),
            nomPrograma = programa.replace("Técnico Laboral en ", "");
        
        $.ajax({
            type: 'POST',
            url: window.public_path + "program/detallePrograma/",
            data: {
                'idPrograma': idPrograma,
                'nomPrograma': programa
            },
            beforeSend: function(){

            },
            success: function(data){
                $('#dv_navegacionsec').removeClass('contendor_navegacionsecdn');
                $('#sp_inicio').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programas').removeClass('contendor_navegacionsecdn').next('span').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').text('Técnico Laborales').addClass('navsecnoactive').removeClass('contendor_navegacionsecdn');
                $('#sp_programa').next('span').removeClass('contendor_navegacionsecdn');
                //$('#sp_programateclab').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#sp_programateclab').text(nomPrograma).removeClass('contendor_navegacionsecdn');
                $('#dv_programa').html(data);
            },
            error: function(){
                console.log('Error');
            }
        }).always(function(){

        });
    });
</script>