<div class="contenedor_imgprograma"></div>
<div class="contenddor_programa">
    <span class="etiqueta_titprog">Técnico Laborales</span>
    <span class="etiqueta_nomprog">Técnico Laboral en Administración de Gestión del Talento Humano</span>
    <span class="etiqueta_nomprog">Técnico Laboral en Gestión Contable y Financiero</span>
    <span class="etiqueta_nomprog">Técnico Laboral en Preparación Física y Entrenamiento Deportivo</span>
    <span class="etiqueta_nomprog">Técnico Laboral en Sistemas</span>
    <span class="etiqueta_nomprog">Técnico Laboral en Vigilancia, Seguridad y Control de Instalaciones</span>
</div>