<div id="dv_contactenos" class="contenedor_pilares contenedor_contactenos">
    <div id="dv_sedepasto" class="contenedor_pilar">
        <span>SEDE PASTO</span>
        <div class="contenedor_infocontactenos">
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_location etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>Cra. 24 No. 14-22</label>
                    <label>Barrio Santiago</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_phone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>720 8428</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_cellphone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>317 862 6794</label>
                </div>
            </div>
        </div>
    </div>
    <div id="dv_sedeipiales" class="contenedor_pilar">
        <span>SEDE IPIALES</span>
        <div class="contenedor_infocontactenos">
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_location etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>Carrera 4a No. 5-34</label>
                    <label>Barrio Gólgota</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_phone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>725 1106 - 775 7495</label>
                </div>
            </div>
        </div>
    </div>
    <div id="dv_emailcontactenos" class="contenedor_pilar">
        <span>SOLICITA INFORMACIÓN</span>
        <div id="dv_diremailcontactenos">
            <label class="icon_email"></label>
            <label>its.atencionusuario@gmail.com</label>
        </div>
        <form id="frm_contactenos">
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Nombre(s) y Apellidos</label>
                <input type="text" name="nombre" id="solicitud_nombre" class="entrada_textoseccioncontactenos" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Correo Electrónico</label>
                <input type="email" name="email" id="solicitud_email" class="entrada_textoseccioncontactenos" autocomplete="off" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Asunto</label>
                <input type="text" name="asunto" id="solicitud_asunto" class="entrada_textoseccioncontactenos" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Mensaje</label>
                <textarea name="mensaje" id="solicitud_mensaje" class="areatexto_mensajeseccioncontactenos" rows="5" required="required"></textarea>
            </div>
            <div class="contenedor_seccioncontactenos">
                <input id="btn_enviar" class="boton_contactenos" type="button" value="Enviar">
                <input id="btn_cancelar" class="boton_contactenos" type="button" value="Cancelar">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label id="lbl_respuestasolicitud">Mensaje de confirmación</label>
            </div>
        </form>
    </div>
</div>
<div id="dv_dialogosolicitud">
    <span>Aqui es...</span>
</div>

<script type="text/javascript">
    $('#frm_contactenos .contenedor_seccioncontactenos:nth-last-of-type(1)').hide();
    
    $('#dv_dialogosolicitud').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        buttons: {
            "Página principal": function() {
                window.location = "<?= PUBLIC_PATH?>";
            },
            "Regresar": function() {
                $(this).dialog("close");
            }
        },
        close: function (){
            //$('body').removeClass('dvcontenedordialogo');
        }
    });
    
    $('#btn_cancelar').on('click', function (){
        document.getElementById("frm_contactenos").reset();
    });
    
    $('#btn_enviar').on('click', function (){
        var nombre = $('#solicitud_nombre').val(),
            email = $('#solicitud_email').val(),
            asunto = $('#solicitud_asunto').val(),
            mensaje = $('#solicitud_mensaje').val();
        
        if(nombre.length > 0 && email.length > 0 && validar_email(email.trim()) && asunto.length > 0 && mensaje.length > 0){
            $.ajax({
                type: 'POST',
                url: window.public_path + 'index/enviarCorreoElectronico/',
                data: $('#frm_contactenos').serialize(),
                dataType: 'json',
                beforeSend: function(){
                    document.getElementById("btn_enviar").disabled = true;
                    
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Enviando solicitud..."
                    });
                },
                success: function(data) {
                    if(data !== null && data.res === 'ok'){
                        $('body').removeClass('menuopen');
                        
                        //$('#dv_dialogosolicitud').dialog('open');
                        
                        $('#lbl_respuestasolicitud').text(data.msg);
                        $('#lbl_respuestasolicitud').removeClass('respuestafail').addClass('respuestaok');
                        $('#frm_contactenos .contenedor_seccioncontactenos:nth-last-of-type(1)').show();
                        
                        document.getElementById("frm_contactenos").reset();
                    }else{
                        $('body').removeClass('menuopen');
                        
                        //$('#dv_dialogosolicitud').dialog('open');
                        
                        $('#lbl_respuestasolicitud').text(data.msg);
                        $('#lbl_respuestasolicitud').removeClass('respuestaok').addClass('respuestafail');
                        $('#frm_contactenos .contenedor_seccioncontactenos:nth-last-of-type(1)').show();
                    }
                    
                    console.log(data.res);
                },
                error: function(){
                    console.log('Ocurrio un error inesperado. Intenta nuevamente');
                }
            }).always(function(){
                document.getElementById("btn_enviar").disabled = false;
                
                $.unblockUI();
            });
        }else{
            $input = $('#solicitud_nombre');
            if(nombre.length === 0){
                $input.addClass('entrada_textoseccioncontactenosnovalido');
            }else{
                $input.removeClass('entrada_textoseccioncontactenosnovalido');
            }
            $input = $('#solicitud_email');
            if(email.length === 0 || !validar_email(email.trim())){
                $input.addClass('entrada_textoseccioncontactenosnovalido');
            }else{
                $input.removeClass('entrada_textoseccioncontactenosnovalido');
            }
            $input = $('#solicitud_asunto');
            if(asunto.length === 0){
                $input.addClass('entrada_textoseccioncontactenosnovalido');
            }else{
                $input.removeClass('entrada_textoseccioncontactenosnovalido');
            }
            $input = $('#solicitud_mensaje');
            if(mensaje.length === 0){
                $input.addClass('entrada_textoseccioncontactenosnovalido');
            }else{
                $input.removeClass('entrada_textoseccioncontactenosnovalido');
            }
        }
    });
    
    $('#solicitud_nombre, #solicitud_asunto, #solicitud_mensaje').on('blur', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_textoseccioncontactenosnovalido');
        } else {
            $(this).removeClass('entrada_textoseccioncontactenosnovalido');
        }
    });
    
    $('#solicitud_email').on('blur', function() {
        var email = $(this).val().trim();
        
        if (!validar_email(email)) {
            $(this).addClass('entrada_textoseccioncontactenosnovalido');
        } else {
            $(this).removeClass('entrada_textoseccioncontactenosnovalido');
        }
    });
    
    $('#solicitud_nombre, #solicitud_email, #solicitud_asunto, #solicitud_mensaje').on('keyup', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_textoseccioncontactenosnovalido');
        } else {
            $(this).removeClass('entrada_textoseccioncontactenosnovalido');
        }
    });
</script>