<div id="dv_contactenos" class="contenedor_pilares contenedor_contactenos">
    <div id="dv_sedepasto" class="contenedor_pilar">
        <span>SEDE PASTO</span>
        <div class="contenedor_infocontactenos">
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_location etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>Calle 21 No. 23-90</label>
                    <label>Respaldo Iglesia Cristo Rey</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_phone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>720 8428</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_cellphone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>317 862 6794</label>
                </div>
            </div>
        </div>
    </div>
    <div id="dv_sedeipiales" class="contenedor_pilar">
        <span>SEDE IPIALES</span>
        <div class="contenedor_infocontactenos">
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_location etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>Carrera 2a No. 12-98</label>
                    <label>Barrio Bellavista</label>
                </div>
            </div>
            <div class="contenedor_seccioninfocontactenos">
                <label class="icon_phone etiqueta_iconinfocontactenos"></label>
                <div>
                    <label>725 1106</label>
                </div>
            </div>
        </div>
    </div>
    <div id="dv_emailcontactenos" class="contenedor_pilar">
        <span>SOLICITA INFORMACIÓN</span>
        <div id="dv_diremailcontactenos">
            <label class="icon_email"></label>
            <label>itsurcolombiano.director@gmail.com</label>
        </div>
        <form id="frm_contactenos">
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Nombre(s) y Apellidos</label>
                <input type="text" class="entrada_textoseccioncontactenos" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Correo Electrónico</label>
                <input type="email" class="entrada_textoseccioncontactenos" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Asunto</label>
                <input type="text" class="entrada_textoseccioncontactenos" required="required">
            </div>
            <div class="contenedor_seccioncontactenos">
                <label class="etiqueta_encabezadoseccioncontactenos">Mensaje</label>
                <textarea class="areatexto_mensajeseccioncontactenos" rows="4" required="required"></textarea>
            </div>
            <div class="contenedor_seccioncontactenos">
                <!--input id="btn_cancelar" class="boton_contactenos" type="button" value="Cancelar" disabled="disabled"-->
                <input id="btn_cancelar" class="boton_contactenos" type="button" value="Cancelar">
                <input id="bn_enviar" class="boton_contactenos" type="button" value="Enviar">
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $('#btn_cancelar').on('click', function (){
        document.getElementById("frm_contactenos").reset();
    });
    
    $('#btn_enviar').on('click', function (){
        console.log('Enviar correo electrónico');
    });
</script>