<div id="dv_slider" class="displaynone">
    <ul id="ul_slider">
        <li>
            <a href="#slide3" onclick="return false;">
                <img src="img/slider/talentohumano.jpg" alt="Técnico Laboral en Administración del Talento Humano">
            </a>
        </li>
        <li>
            <a href="#slide3" onclick="return false;">
                <img src="img/slider/contabilidad.jpg" alt="Técnico Laboral en Gestión Contable y Financiera">
            </a>
        </li>
        <li>
            <a href="#slide2" onclick="return false;">
                <img src="img/slider/deportes.jpg" alt="Técnico Laboral en Preparación Fisica y Entrenamiento Deportivo">
            </a>
        </li>
        <li>
            <a href="#slide1" onclick="return false;">
                <img src="img/slider/sistemas.jpg" alt="Técnico Laboral en Sistemas">
            </a>
        </li>
        <li>
            <a href="#slide3" onclick="return false;">
                <img src="img/slider/vigilancia.jpg" alt="Técnico Laboral en Vigilancia Seguridad y Control de Instalaciones">
            </a>
        </li>
    </ul>
</div>
<div id="dv_facilidades">
    <div class="contenedor_facilidades">
        <span>Horarios Flexibles</span>
        <span>Diurno</span>
        <span>Nocturno</span>
        <span>Fines de Semana</span>
    </div>
    <div class="contenedor_facilidades">Facilidad de Pagos</div>
</div>
<div id="dv_contenido">
    <div id="dv_texto">
        La calidad de la educativa esta en el alcance de las competencias laborales a través de habilidades, destrezas, actitudes, aptitudes, conocimientos y el ser como persona con valores para desempeñarse en el medio productivo.
    </div>
    <div class="contenedor_pilares">
        <div id="dv_pilareducacion" class="contenedor_pilar">
            <span>EDUCACIÓN</span>
            <div>La educación dentro de un contexto físico, social, afectivo propio de la situación de aprendizaje, establecido por el INSTITUTO TECNOLOGICO SUR COLOMBIANO, con calidad y compromiso social que deberá alcanzar el estudiante.</div>
        </div>
        <div id="dv_pilartecnologia" class="contenedor_pilar">
            <span>TECNOLOGÍA</span>
            <div>La Tecnologías en la parte educativa permite globalizar al mundo de la información, facilitando la comunicación entre las personas e instituciones no solo a nivel de la comunidad o el estado sino que también a nivel mundial.</div>
        </div>
        <div id="dv_pilarcompetencias" class="contenedor_pilar">
            <span>COMPETENCIAS</span>
            <div>Las competencias laborales, abarca el rol y la situación laboral /técnica que nos lleva ha capacitar con procesos de formación para alcanzar el logro de las competencias Laborales, así como sus componentes.</div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(window).load(function(){
        $('#dv_slider').removeClass('displaynone');
    });
    
    require([
        window.public_path+'javascript/slippry.min.js'
    ],function(){
        jQuery('#ul_slider').slippry({
            slippryWrapper: '<div class="sy-box ul_slider" />',
            //adaptiveHeight: false,
            useCSS: false,
            autoHover: false,
            transition: 'fade',
            //captions: false,
            //preload: 'all',
            controls: false,
            speed: 1000,
            //pager: false,
            auto: true
        });
    });
</script>