<div id="dv_mapa"></div>
<?/* <div id="dv_streetview"></div> */?>

<script type="text/javascript">
    var myLatLng, map, market;
    
    //function initMap() {
        <? if($sede == 0): ?>
            //myLatLng = {lat: 1.2149208, lng: -77.2759726};
            myLatLng = {lat: 1.2125873, lng: -77.2817441};
        <? else: ?>
            //myLatLng = {lat: 0.8276849, lng: -77.6368448};
            myLatLng = {lat: 0.8240399, lng: -77.6326227};
        <? endif; ?>

        map = new google.maps.Map(document.getElementById('dv_mapa'), {
            center: myLatLng,
            scrollwheel: false,
            zoom: 18
        });
        
        var content = '';
        
        <? if($sede == 0): ?>
            content = '<div style="color: green; font-size: 18px">Pasto</div>';
        <? else: ?>
            content = '<div style="color: green; font-size: 18px">Ipiales</div>';
        <? endif; ?>
        
        var infowindow = new google.maps.InfoWindow({
            content: content,
            maxWidth: 100
        });

        marker = new google.maps.Marker({
            map: map,
            position: myLatLng,
            title: 'Instituto Técnico Surcolombiano, Sede <?= ($sede==0)?'Pasto':'Ipiales';?>'
        });

        /*panorama = new google.maps.StreetViewPanorama(document.getElementById('dv_streetview'), {
            position: myLatLng,
            pov: {
                heading: 30,
                pitch: 10,
                zoom: 0.5
            }
        });

        map.setStreetView(panorama);*/
        
        google.maps.event.addListener(infowindow, 'domready', function(){
            $(".gm-style-iw").next("div").hide();
        });
        
        google.maps.event.addDomListener(marker, 'mouseover', function() {
            infowindow.open(map, marker);
        });
        
        google.maps.event.addDomListener(marker, 'mouseout', function() {
            infowindow.close();
        });
        
        google.maps.event.addDomListener(window, "resize", function() {
            var center = map.getCenter();
            
            google.maps.event.trigger(map, "resize");
            map.setCenter(center); 
        });
    //}
</script>