<div id="dv_visitanos">
    <div id="dv_contenidomapa">
        <div id="dv_tabsmap">
            <span id="sp_tabsedepasto" class="etiqueta_tabactive">Sede Pasto</span>
            <span id="sp_tabsedeipiales" class="etiqueta_tabnoactive">Sede Ipiales</span>
        </div>
        <!--span class="etiqueta_localizacion">Localización</span-->
        <span id="sp_ciulocalizacion" class="etiqueta_localizacion">San Juan de Pasto, Nariño, Colombia</span>
        <span id="sp_dirlocalizacion" class="etiqueta_localizacion">Calle 21 No. 23-90</span>
        <div id="dv_seccionmapa">
            <? //View::partial('map'); ?>
            <!--div id="dv_mapa"></div-->
            <!--div id="dv_streetview"></div-->
        </div>
    </div>
</div>

<script type="text/javascript">
    $.ajax({
        type: 'POST',
        url: window.public_path + "index/map/",
        data: {
            'sede': 0
        },
        beforeSend: function(){

        },
        success: function(data){
            $('#dv_seccionmapa').html(data);
        },
        error: function(){
            console.log('Error');
        }
    }).always(function(){

    });
    
    $('#sp_tabsedepasto').on('click', function(){
        if(window.tablocalizacion > 0){
            window.tablocalizacion = 0;
            
            $('#sp_tabsedeipiales').removeClass('etiqueta_tabactive').addClass('etiqueta_tabnoactive');
            $(this).removeClass('etiqueta_tabnoactive').addClass('etiqueta_tabactive');
            
            $('#sp_ciulocalizacion').text('San Juan de Pasto, Nariño, Colombia');
            $('#sp_dirlocalizacion').text('Calle 21 No. 23-90');
            
            $.ajax({
                type: 'POST',
                url: window.public_path + "index/map/",
                data: {
                    'sede': 0
                },
                beforeSend: function(){

                },
                success: function(data){
                    $('#dv_seccionmapa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
        }
    });
    
    $('#sp_tabsedeipiales').on('click', function(){
        if(window.tablocalizacion < 1){
            window.tablocalizacion = 1;
            
            $('#sp_tabsedepasto').removeClass('etiqueta_tabactive').addClass('etiqueta_tabnoactive');
            $(this).removeClass('etiqueta_tabnoactive').addClass('etiqueta_tabactive');
            
            $('#sp_ciulocalizacion').text('Ipiales, Nariño, Colombia');
            $('#sp_dirlocalizacion').text('Carrera 2a No. 12-98 B/Bellavista');
            
            $.ajax({
                type: 'POST',
                url: window.public_path + "index/map/",
                data: {
                    'sede': 1
                },
                beforeSend: function(){

                },
                success: function(data){
                    $('#dv_seccionmapa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
        }
    });
</script>

<!--script type="text/javascript">
    var myLatLng, map, market;
    
    function initMap() {
        myLatLng = {lat: 1.2149208, lng: -77.2759726};

        map = new google.maps.Map(document.getElementById('dv_mapa'), {
            center: myLatLng,
            scrollwheel: false,
            zoom: 18
        });

        marker = new google.maps.Marker({
            map: map,
            position: myLatLng,
            title: 'Instituto Técnico Surcolombiano'
        });

        /*panorama = new google.maps.StreetViewPanorama(document.getElementById('dv_streetview'), {
            position: myLatLng,
            pov: {
                heading: 30,
                pitch: 10,
                zoom: 0.5
            }
        });

        map.setStreetView(panorama);*/
        
        google.maps.event.addDomListener(window, "resize", function() {
            var center = map.getCenter();
            
            google.maps.event.trigger(map, "resize");
            map.setCenter(center); 
        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYXHhoAbijaDCTdv98TsW_oucwePlcnD4&callback=initMap" async defer>
</script-->