<div id="dv_visitanos">
    <div id="dv_contenidomapa">
        <div id="dv_tabsmap">
            <span id="sp_tabsedepasto" class="etiqueta_tabactive">Sede Pasto</span>
            <span id="sp_tabsedeipiales" class="etiqueta_tabnoactive">Sede Ipiales</span>
        </div>
        <span id="sp_ciulocalizacion" class="etiqueta_localizacion">San Juan de Pasto, Nariño, Colombia</span>
        <span id="sp_dirlocalizacion" class="etiqueta_localizacion">Cra. 24 No. 14-22</span>
        <div id="dv_seccionmapa"></div>
    </div>
</div>

<script type="text/javascript">
    $.ajax({
        type: 'POST',
        url: window.public_path + "index/map/",
        data: {
            'sede': 0
        },
        beforeSend: function(){

        },
        success: function(data){
            $('#dv_seccionmapa').html(data);
        },
        error: function(){
            console.log('Error');
        }
    }).always(function(){

    });
    
    $('#sp_tabsedepasto').on('click', function(){
        if(window.tablocalizacion > 0){
            window.tablocalizacion = 0;
            
            $('#sp_tabsedeipiales').removeClass('etiqueta_tabactive').addClass('etiqueta_tabnoactive');
            $(this).removeClass('etiqueta_tabnoactive').addClass('etiqueta_tabactive');
            
            $('#sp_ciulocalizacion').text('San Juan de Pasto, Nariño, Colombia');
            $('#sp_dirlocalizacion').text('Cra. 24 No. 14-22');
            
            $.ajax({
                type: 'POST',
                url: window.public_path + "index/map/",
                data: {
                    'sede': 0
                },
                beforeSend: function(){

                },
                success: function(data){
                    $('#dv_seccionmapa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
        }
    });
    
    $('#sp_tabsedeipiales').on('click', function(){
        if(window.tablocalizacion < 1){
            window.tablocalizacion = 1;
            
            $('#sp_tabsedepasto').removeClass('etiqueta_tabactive').addClass('etiqueta_tabnoactive');
            $(this).removeClass('etiqueta_tabnoactive').addClass('etiqueta_tabactive');
            
            $('#sp_ciulocalizacion').text('Ipiales, Nariño, Colombia');
            $('#sp_dirlocalizacion').text('Cra. 4a. No. 5-34 B/Gólgota');
            
            $.ajax({
                type: 'POST',
                url: window.public_path + "index/map/",
                data: {
                    'sede': 1
                },
                beforeSend: function(){

                },
                success: function(data){
                    $('#dv_seccionmapa').html(data);
                },
                error: function(){
                    console.log('Error');
                }
            }).always(function(){

            });
        }
    });
</script>