<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=<?php echo APP_CHARSET ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    
    <title>Instituto Técnico Surcolombiano</title>
    
    <? Tag::css("general") ?>
    <? Tag::css("principal") ?>
    <? Tag::css("programa") ?>
    <? Tag::css("registro") ?>
    <? Tag::css("slippry") ?>
    
    <?= Html::includeCss() ?>
    
    <?= Tag::js('jquery/jquery-2.2.3.min') ?>
    <?= Tag::js('html5shiv') ?>
    <?//= Tag::js('funciones') ?>
    <?= Tag::js('require') ?>
    
    <script type="text/javascript">
        window.public_path = '<?= PUBLIC_PATH?>';
    </script>
    
    <? (isset($programas))?$banProgramas = $programas:$banProgramas = 0;
    (isset($tipoProg))?$tipoPrograma = $tipoProg:$tipoPrograma = 0;
    (isset($institucion))?$banInstitucion = $institucion:$banInstitucion = 0;
    (isset($tipoIns))?$tipoInstitucion = $tipoIns:$tipoInstitucion = 0; ?>
</head>
<body>
    <header>
        <? View::partial("header", false, array('banProgramas'=>$banProgramas, 'tipoPrograma'=>$tipoPrograma, 'banInstitucion'=>$banInstitucion, 'tipoInstitucion'=>$tipoInstitucion)) ?>
    </header>
    <section id="sec_contenido">
        <? View::content(); ?>
    </section>
    <footer>
        <? View::partial("footer") ?>
    </footer>
    
    <!--script type="text/javascript">
        //alert(<?= (isset($programas))?$programas:0;?>);
        //alert(<?= $banProgramas;?>);
        console.log('banProgramas: ' + <?= $banProgramas;?>);
        console.log('banInstitucion: ' + <?= $banInstitucion;?>);
    </script-->
</body>
</html>