<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=<?php echo APP_CHARSET ?>" />
    
    <title>Instituto Técnico Surcolombiano</title>
    
    <? Tag::css("general") ?>
    <? Tag::css("principal") ?>
    <? Tag::css("slippry") ?>
    
    <?= Html::includeCss() ?>
    
    <?= Tag::js('jquery/jquery-2.2.3.min') ?>
    <?= Tag::js('require') ?>
    
    <script type="text/javascript">
        window.public_path = '<?= PUBLIC_PATH?>';
    </script>
    
    <? (isset($programas))?$banProgramas = $programas:$banProgramas = 0; ?>
</head>
<body>
    <header>
        <? View::partial("header", false, array('banProgramas'=>$banProgramas)) ?>
    </header>
    <section id="sec_contenido">
        <? View::content(); ?>
    </section>
    <footer>
        <? View::partial("footer") ?>
    </footer>
    
    <!--script type="text/javascript">
        //alert(<?= (isset($programas))?$programas:0;?>);
        //alert(<?= $banProgramas;?>);
    </script-->
</body>
</html>