<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    
    <title>Página no encontrada - Instituto Técnico Surcolombiano</title>
    
    <? Tag::css("general") ?>
    <? Tag::css("404") ?>
    <? //Tag::css("principal") ?>
    <? //Tag::css("programa") ?>
    <? //Tag::css("registro") ?>
    <? //Tag::css("slippry") ?>
    <? Tag::css("responsive") ?>
    
    <?= Html::includeCss() ?>
    
    <link rel="icon" type="img/ico" href="<?= PUBLIC_PATH . "img/favicon.ico "?>">
    
    <?= Tag::js('jquery/jquery-2.2.3.min') ?>
    <?= Tag::js('html5shiv') ?>
</head>
<body>
    <header>
        <? View::partial("header", false, array('view'=>0, 'banProgramas'=>0, 'tipoPrograma'=>0, 'banInstitucion'=>0, 'tipoInstitucion'=>0, 'banContactenos'=>0)) ?>
    </header>
    <section id="sec_contenido404">
        <div id="dv_contenido404">
            <span id="sp_advertencia404"></span>
            <span id="sp_encabezado404">UPS!</span>
            <div>
                <span class="etiqueta_texto404">Página no encontrada</span>
                <span class="etiqueta_texto404">Parece que ha habido un error con la página que estabas buscando.</span>
                <span class="etiqueta_texto404">Es posible que la entrada haya sido eliminada o que la direccion no exista.</span>
            </div>
            <a href="<?= PUBLIC_PATH?>">Ir a la página principal</a>
        </div>
    </section>
    <footer>
        <? View::partial("footer", false, array('view'=>0)) ?>
    </footer>
</body>
</html>
