<div class="contenedor_sistemacalificacion">
    <span>REGISTRO DE NOTAS</span>
    <label class="etiqueta_textosistemacalificacion">Mediante esta página usted puede registrar y/o actualizar calificaciones</label>
    <form id="frm_logindocente">
        <div class="contendor_elementosistemacalificacion">
            <label class="etiqueta_textoelementosistemacalificacion">Identificación</label>
            <input id="txt_iddocente" class="entrada_datossistemacalificacion" type="text" placeholder="Digite aquí su identificación" autofocus required="required">
        </div>
        <div class="contendor_elementosistemacalificacion">
            <label class="etiqueta_textoelementosistemacalificacion">Contraseña</label>
            <input id="txt_passdocente" class="entrada_datossistemacalificacion" type="password" placeholder="Digite aquí su contraseña" required="required">
        </div>
        <div class="contendor_elementosistemacalificacion">
            <input id="btn_logindocente" class="boton_sistemacalificacion" type="button" value="Ingresar">
        </div>
    </form>
</div>

<script type="text/javascript">
    $('#btn_logindocente').on('click', function (){
        var id = $('#txt_iddocente').val(),
            pass = $('#txt_passdocente').val();
        
        if(id.length > 0 && pass.length > 0){
            $.ajax({
                type: 'POST',
                url: window.public_path + 'grade/logearDocente/',
                data: {
                    identificacion: id,
                    contrasena: pass
                },
                dataType: 'json',
                beforeSend: function(){
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Validando datos..."
                    });
                },
                success: function(data) {
                    //$('body').removeClass('menuopen');
                    
                    if(data !== null && data.res === 'ok'){
                        window.location = "<?= PUBLIC_PATH?>docentes/registro_notas/";
                    }else{
                        console.log(data.msg);
                    }
                },
                error: function(){
                    console.log('Ocurrio un error inesperado. Intenta nuevamente -');
                }
            }).always(function(){
                $.unblockUI();
            });
        }else{
            $input = $('#txt_iddocente');
            if(id.length === 0){
                $input.addClass('entrada_camponovalido');
            }else{
                $input.removeClass('entrada_camponovalido');
            }
            $input = $('#txt_passdocente');
            if(pass.length === 0){
                $input.addClass('entrada_camponovalido');
            }else{
                $input.removeClass('entrada_camponovalido');
            }
        }
    });
    
    $('#txt_iddocente, #txt_passdocente').on('blur', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_camponovalido');
        } else {
            $(this).removeClass('entrada_camponovalido');
        }
    });
    
    $('#txt_iddocente, #txt_passdocente').on('keyup', function() {
        var txt = $(this).val();
        
        if (txt.length <= 0) {
            $(this).addClass('entrada_camponovalido');
        } else {
            $(this).removeClass('entrada_camponovalido');
        }
    });
</script>