<div class="contenedor_sistemacalificacion">
    <span>Registro DE NOTAS</span>
    <label class="etiqueta_textosistemacalificacion">Mediante esta página usted puede registrar y/o actualizar calificaciones</label>
    <form id="frm_logindocente">
        <div class="contendor_elementosistemacalificacion">
            <label class="etiqueta_textoelementosistemacalificacion">Identificación</label>
            <input id="txt_iddocente" class="entrada_datossistemacalificacion" type="text" placeholder="Digite aquí su identificación" required="required">
        </div>
        <div class="contendor_elementosistemacalificacion">
            <label class="etiqueta_textoelementosistemacalificacion">Contraseña</label>
            <input id="txt_passdocente" class="entrada_datossistemacalificacion" type="password" placeholder="Digite aquí su contraseña" required="required">
        </div>
        <div class="contendor_elementosistemacalificacion">
            <input id="btn_logindocente" class="boton_sistemacalificacion" type="button" value="Ingresar">
        </div>
    </form>
</div>