<div id="dv_registrodenotas">
    <? if($numeroalumnos[0]->resultado === '0'): ?>
        <span class="etiqueta_estadonotasalumno">No hay estudiantes que validen esta materia</span>
    <? else: ?>
        <div id="dv_cortesseestre">
            <span>Tipo de Nota</span>
            <input id="txt_cortessemestre" class="texto_cortessemestre" type="text" readonly="readonly" value="Validación">
        </div>
        <? foreach($alumnos as $alumno): ?>
            <div class="contenedor_registrodenotas">
                <span class="etiqueta_idalumno"><?= $alumno->identificacion_alumno?></span>
                <span class="etiqueta_namealumno"><?= $alumno->nombre_alumno . ' ' . $alumno->apellido_alumno?></span>
                <input id="txt_notaalumno<?= $alumno->id_alumno?>" class="texto_gradealumno" type="number" data-idalumno="<?=$alumno->id_alumno?>" data-idvalidacion="<?=$alumno->id_validacion?>" maxlength="3" step="0.1" min="0" max="5" value="0" onkeyup="validarNota.call(this);">
            </div>
        <? endforeach; ?>
        <div id="dv_registrarnotasalumno">
            <input id="btn_registrarnotasalumno" type="button" value="Registrar">
        </div>
    <? endif; ?>
</div>
<div id="dv_dialogoconfirmacionregistronotas">
    <span>Registro de calificaciones de validaciones extoso. Aceptar para continuar con el registro o salir del sistema de registro de calificaciones</span>
</div>

<script type="text/javascript">
    $('#dv_dialogoconfirmacionregistronotas').dialog({
        autoOpen: false,
        modal: true,
        resizable: false,
        closeOnEscape: false,
        buttons: {
            "Aceptar": function() {
                window.location = "<?= PUBLIC_PATH?>docentes/registro_notas/validaciones/";
            }
        },
        close: function (){}
    });
    
    $('#btn_registrarnotasalumno').on('click', function (){
        var banderanotas = 1;
        
        <? foreach($alumnos as $alumno): ?>
            var nota = $('#txt_notaalumno' + <?= $alumno->id_alumno?>).val();
            
            if(nota.length === 0 || convertiranumero(nota) < 0 || convertiranumero(nota) > 5){
                banderanotas = 0;
            }
        <? endforeach; ?>
        
        if(banderanotas > 0){
            var notas = new Array();
            
            <? foreach($alumnos as $alumno): ?>
                var idvalidacion = $('#txt_notaalumno' + <?= $alumno->id_alumno?>).data('idvalidacion'),
                    nota = $('#txt_notaalumno' + <?= $alumno->id_alumno?>).val(),
                    idalumno = $('#txt_notaalumno' + <?= $alumno->id_alumno?>).data('idalumno');

                notas.push({
                    idvalidacion: idvalidacion,
                    valor: puntoporcoma(nota),
                    idalumno: idalumno
                });
            <? endforeach; ?>
            
            $.ajax({
                type: 'POST',
                url: <?= PUBLIC_PATH?> + 'grade/registrarNotasValidacionesAlumnos/',
                data: {
                    notas: JSON.stringify(notas)
                },
                dataType: 'json',
                beforeSend: function(){
                    //document.getElementById("btn_consultarnotas").disabled = true;
                    
                    $('body').addClass('menuopen');
                    
                    $.blockUI({
                        message: "Registrando calificación(es)..."
                    });
                },
                success: function(data) {
                    $('body').removeClass('menuopen');
                    //document.getElementById("frm_codigoestudiante").reset();

                    if(data !== null && data.res === 'ok'){
                        $('#dv_dialogoconfirmacionregistronotas').dialog('open');
                        
                        console.log(data.res);
                    }else{
                        console.log(data.msg);
                    }
                },
                error: function(){
                    //console.log('Ocurrio un error inesperado. Intenta nuevamente');
                }
            }).always(function(){
                //document.getElementById("btn_consultarnotas").disabled = false;

                $.unblockUI();
            });
        }else{
            $inputfocus = null;
            /*$input = $('#slt_cortessemestre');
            if(convertiranumero(tiponota) === 0){
                $input.addClass('etiqueta_tiponotanovalido');
                if($inputfocus === null)$inputfocus = $input;
            }else{
                $input.removeClass('etiqueta_tiponotanovalido');
            }*/
            <? foreach($alumnos as $alumno): ?>
                var nota = $('#txt_notaalumno' + <?= $alumno->id_alumno?>).val();
                
                $input = $('#txt_notaalumno' + <?= $alumno->id_alumno?>);
                if(nota.length === 0 || convertiranumero(nota) < 0 || convertiranumero(nota) > 5){
                    $input.addClass('etiqueta_tiponotanovalido');
                    if($inputfocus === null)$inputfocus = $input;
                }else{
                    $input.removeClass('etiqueta_tiponotanovalido');
                }
            <? endforeach; ?>

            if($inputfocus !== null){
                $('html, body').animate({scrollTop: $inputfocus.position().top+'px'}, 1000);
                $inputfocus.focus();
            }
        }
    });
    
    function validarNota(){
        if($(this).val().length > 0 && convertiranumero($(this).val()) >= 0 && convertiranumero($(this).val()) <= 5){
            $(this).removeClass('etiqueta_tiponotanovalido');
        }else{
            $(this).addClass('etiqueta_tiponotanovalido');
        }
    }
</script>